version: '3'

services:
  db_api:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'db_api'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data: